name: Deploy

on:

  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: sudo
      run: sudo -i
    - run: whoami
    - run: hostname
    - run: lscpu
    - run: sleep 10
